"""updates recipe model

Revision ID: 3a6e79e7bc07
Revises: cf731db1a9a1
Create Date: 2021-08-12 14:02:26.804844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6e79e7bc07'
down_revision = 'cf731db1a9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_plan_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'plan_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_plan_id_fkey', 'recipe', 'plan', ['plan_id'], ['plan_id'])
    # ### end Alembic commands ###
