"""updates recipe model

Revision ID: d1c6ccd61c5e
Revises: 3a6e79e7bc07
Create Date: 2021-08-12 14:08:04.184830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c6ccd61c5e'
down_revision = '3a6e79e7bc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'plan', ['plan_id'], ['plan_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'plan_id')
    # ### end Alembic commands ###
